"""create problems and submissions tables

Revision ID: 65b4f4d728de
Revises: a49aec5df21e
Create Date: 2026-10-09 09:36:06.893269

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65b4f4d728de"
down_revision: str | Sequence[str] | None = "a49aec5df21e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problems",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum(
                "easy",
                "medium",
                "hard",
                name="problem_difficulty",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column(
            "is_published",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'medium', 'hard')",
            name=op.f("ck_problems_valid_difficulty"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'",
            name=op.f("ck_problems_slug_format"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(statement)) > 0",
            name=op.f("ck_problems_non_empty_statement"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(title)) > 0",
            name=op.f("ck_problems_non_empty_title"),
        ),
        sa.CheckConstraint(
            "memory_limit_mb > 0",
            name=op.f("ck_problems_positive_memory_limit"),
        ),
        sa.CheckConstraint(
            "time_limit_ms > 0", name=op.f("ck_problems_positive_time_limit")
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_problems_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_problems_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problems")),
        sa.UniqueConstraint("slug", name=op.f("uq_problems_slug")),
    )
    op.create_index(
        op.f("ix_problems_author_id"), "problems", ["author_id"], unique=False
    )
    op.create_index(
        "ix_problems_published_difficulty",
        "problems",
        ["is_published", "difficulty"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("problem_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "accepted",
                "wrong_answer",
                "time_limit_exceeded",
                "memory_limit_exceeded",
                "runtime_error",
                "system_error",
                name="submission_status",
                native_enum=False,
                length=32,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "score", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("problem_version", sa.Integer(), nullable=False),
        sa.Column("test_set_revision", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'accepted', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded', 'runtime_error', 'system_error')",
            name=op.f("ck_submissions_valid_status"),
        ),
        sa.CheckConstraint(
            "char_length(btrim(language)) > 0",
            name=op.f("ck_submissions_non_empty_language"),
        ),
        sa.CheckConstraint(
            "char_length(source_code) > 0",
            name=op.f("ck_submissions_non_empty_source_code"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_submissions_valid_execution_window"),
        ),
        sa.CheckConstraint(
            "problem_version > 0",
            name=op.f("ck_submissions_positive_problem_version"),
        ),
        sa.CheckConstraint(
            "score BETWEEN 0 AND 100", name=op.f("ck_submissions_valid_score")
        ),
        sa.CheckConstraint(
            "test_set_revision > 0",
            name=op.f("ck_submissions_positive_test_set_revision"),
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
            name=op.f("fk_submissions_problem_id_problems"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_submissions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
    )
    op.create_index(
        "ix_submissions_problem_created_at",
        "submissions",
        ["problem_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_submissions_status_created_at",
        "submissions",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_submissions_user_created_at",
        "submissions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "submission_cases",
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "passed",
                "wrong_answer",
                "time_limit_exceeded",
                "memory_limit_exceeded",
                "runtime_error",
                "system_error",
                "skipped",
                name="submission_case_verdict",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("memory_kb", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('passed', 'wrong_answer', 'time_limit_exceeded', 'memory_limit_exceeded', 'runtime_error', 'system_error', 'skipped')",
            name=op.f("ck_submission_cases_valid_verdict"),
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_submission_cases_non_negative_duration"),
        ),
        sa.CheckConstraint(
            "memory_kb IS NULL OR memory_kb >= 0",
            name=op.f("ck_submission_cases_non_negative_memory"),
        ),
        sa.CheckConstraint(
            "ordinal >= 0",
            name=op.f("ck_submission_cases_non_negative_ordinal"),
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_cases_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_cases")),
        sa.UniqueConstraint(
            "submission_id", "ordinal", name="submission_ordinal"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submission_cases")
    op.drop_index("ix_submissions_user_created_at", table_name="submissions")
    op.drop_index("ix_submissions_status_created_at", table_name="submissions")
    op.drop_index(
        "ix_submissions_problem_created_at", table_name="submissions"
    )
    op.drop_table("submissions")
    op.drop_index("ix_problems_published_difficulty", table_name="problems")
    op.drop_index(op.f("ix_problems_author_id"), table_name="problems")
    op.drop_table("problems")
    # ### end Alembic commands ###
